// <auto-generated />
using lxEF.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace lxEF.Server.Migrations
{
    [DbContext(typeof(lxDbContext))]
    [Migration("20231216132001_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("lxEF.Server.Data.Models.DBUser", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IP");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsAuthenticated");

                    b.Property<bool>("IsBanned");

                    b.Property<string>("License");

                    b.Property<string>("SteamID");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("DBUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
